### ISSUE TITLE
Module 3 : Mocha failed on local

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/aws-serverless-workshops#138]
At this [step](https://github.com/aws-samples/aws-serverless-workshops/tree/master/DevOps/3_XRay#validation-using-x-ray), when I try to validate the code with Mocha on Cloud9

```
Admin:~/environment/uni-api (master) $ node_modules/.bin/mocha


  Deleting Unicorns
    1) "before all" hook

  Listing Unicorns
    2) "before all" hook

  Reading Unicorns
Received event: {
  "resource": "unicorns",
  "httpMethod": "GET",
  "pathParameters": {
    "name": "FakeName"
  }
}
{"TableName":"UnicornsTable","Key":{"name":"FakeName"}}
    ✓ reads existing unicorn data
Received event: {
  "resource": "unicorns",
  "httpMethod": "GET",
  "pathParameters": {
    "name": "MissingUnicorn"
  }
}
{"TableName":"UnicornsTable","Key":{"name":"MissingUnicorn"}}
    ✓ errors on missing unicorn data

  Updating Unicorns
    3) "before all" hook


  2 passing (172ms)
  3 failing

  1) Deleting Unicorns
       "before all" hook:
     TypeError: Invalid Version: undefined
      at new SemVer (app/node_modules/semver/semver.js:291:11)
      at compare (app/node_modules/semver/semver.js:578:10)
      at Function.gte (app/node_modules/semver/semver.js:627:10)
      at Object.captureAWS (app/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:31:15)
      at Object.<anonymous> (app/delete.js:4:21)
      at Object.require.extensions.(anonymous function) (node_modules/proxyquire/lib/proxyquire.js:276:43)
      at Proxyquire._withoutCache (node_modules/proxyquire/lib/proxyquire.js:179:12)
      at Proxyquire.load (node_modules/proxyquire/lib/proxyquire.js:136:15)
      at Context.before (test/delete.spec.js:17:15)

  2) Listing Unicorns
       "before all" hook:
     TypeError: Invalid Version: undefined
      at new SemVer (app/node_modules/semver/semver.js:291:11)
      at compare (app/node_modules/semver/semver.js:578:10)
      at Function.gte (app/node_modules/semver/semver.js:627:10)
      at Object.captureAWS (app/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:31:15)
      at Object.<anonymous> (app/list.js:4:21)
      at Object.require.extensions.(anonymous function) (node_modules/proxyquire/lib/proxyquire.js:276:43)
      at Proxyquire._withoutCache (node_modules/proxyquire/lib/proxyquire.js:179:12)
      at Proxyquire.load (node_modules/proxyquire/lib/proxyquire.js:136:15)
      at Context.before (test/list.spec.js:15:15)

  3) Updating Unicorns
       "before all" hook:
     TypeError: Invalid Version: undefined
      at new SemVer (app/node_modules/semver/semver.js:291:11)
      at compare (app/node_modules/semver/semver.js:578:10)
      at Function.gte (app/node_modules/semver/semver.js:627:10)
      at Object.captureAWS (app/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:31:15)
      at Object.<anonymous> (app/update.js:4:21)
      at Object.require.extensions.(anonymous function) (node_modules/proxyquire/lib/proxyquire.js:276:43)
      at Proxyquire._withoutCache (node_modules/proxyquire/lib/proxyquire.js:179:12)
      at Proxyquire.load (node_modules/proxyquire/lib/proxyquire.js:136:15)
      at Context.before (test/update.spec.js:19:15)
```

**Comment by WChoy** [comment]
The problem is the order that the Mocha Unit Tests are run.
TRY renaming them to "1_update.spec.js", "2_list.spec.js, "3_read.spec.js" and "4_delete.spec.js".

The proper fix would be to make each Unit test:
(1) independent of each other,
(2a) mocking the Data in DynamoDB (try the aws-sdk-mock package).
(2b) Or use the "before()" and the "after" hooks to create and clean your data

**Comment by WChoy** [comment]
It's failing on the version of the aws-sdk specified in the mocha test (uni-app/test/*.spec.js)  to mock the DynamoDB Table.
`  // Create a mock DDB backend
    aws = proxyquire(PATH_TO_MODULE_UNDER_TEST, {
            'aws-sdk' :{
                "VERSION" : "2.155.0",
                "DynamoDB": {
`
Since 'aws-sdk' is not in the package json, check the version (npm list aws-sdk) used by your the Cloud9 environment.  

Change the code to "VERSION": "2.290.0"... or leave it.

**Comment by samdengler** [comment]
Thanks for your feedback.  We've update the DevOps Serverless Workshop with new content: https://cicd.serverlessworkshops.io/
