### ISSUE TITLE
Running "hello World" API Gateway locally on windows

### ISSUE THREAD

**Issue by pwhitehead** [aws-samples/aws-serverless-workshops#160]
I'm trying to run through Module-1 for aws-serverless-workshops, but after starting the local sam:
> sam local start-api

and then typing "http://127.0.0.1:3000/unicorns" into chrome browser, I'm getting an "Unable to import module 'list' error.  I've searched for others with same issue, but can't find anything that seems to help. 
 See console results below.   Any help would be appreciated:

=============
2018-11-05 13:58:31 Mounting ListFunction at http://127.0.0.1:3000/unicorns [GET]
2018-11-05 13:58:31 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2018-11-05 13:58:31  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-11-05 13:58:49 Invoking list.lambda_handler (nodejs6.10)
2018-11-05 13:58:49 Found credentials in shared credentials file: ~/.aws/credentials

Fetching lambci/lambda:nodejs6.10 Docker container image......
2018-11-05 13:58:52 Mounting D:\Data\Apps\eclipse-workspace\uni-api\app as /var/task:ro inside runtime container
[32mSTART RequestId: 6964d254-6e3d-1550-463c-93a62fd2ca27 Version: $LATEST[0m
[31mUnable to import module 'list': Error[0m
[31m    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)[0m
[32mEND RequestId: 6964d254-6e3d-1550-463c-93a62fd2ca27[0m
[32mREPORT RequestId: 6964d254-6e3d-1550-463c-93a62fd2ca27     Duration: 12.27 ms      Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 27 MB  [0m
2018-11-05 13:58:53 Invoking list.lambda_handler (nodejs6.10)
2018-11-05 13:58:53 Found credentials in shared credentials file: ~/.aws/credentials
2018-11-05 13:58:53 No Content-Type given. Defaulting to 'application/json'.
2018-11-05 13:58:53 127.0.0.1 - - [05/Nov/2018 13:58:53] "GET /unicorns HTTP/1.1" 200 -

Fetching lambci/lambda:nodejs6.10 Docker container image......
2018-11-05 13:58:56 Mounting D:\Data\Apps\eclipse-workspace\uni-api\app as /var/task:ro inside runtime container
[32mSTART RequestId: ac78518f-268b-1e38-af92-915fbd7f9a43 Version: $LATEST[0m
[31mUnable to import module 'list': Error[0m
[31m    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)[0m
[32mEND RequestId: ac78518f-268b-1e38-af92-915fbd7f9a43[0m
[32mREPORT RequestId: ac78518f-268b-1e38-af92-915fbd7f9a43     Duration: 12.09 ms      Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 31 MB  [0m
2018-11-05 13:58:57 No Content-Type given. Defaulting to 'application/json'.
2018-11-05 13:58:57 127.0.0.1 - - [05/Nov/2018 13:58:57] "GET /unicorns HTTP/1.1" 200 -
2018-11-05 13:58:57 127.0.0.1 - - [05/Nov/2018 13:58:57] "GET /favicon.ico HTTP/1.1" 403 -

**Comment by samdengler** [comment]
Hi @pwhitehead - I'm taking a look.

**Comment by daveshield** [comment]
Hi, 

Im having the exact same issue. Did you manage to figure out what was happening?


2018-11-27 15:01:13 Invoking list.lambda_handler (nodejs6.10)
2018-11-27 15:01:25 Failed to download a new lambci/lambda:nodejs6.10 image. Invoking with the already downloaded image.
2018-11-27 15:01:25 Mounting C:\Users\ds\Documents\code\uni-api\app as /var/task:ro inside runtime container
START RequestId: ba085c42-8de0-1153-cfa6-fd5c214ad777 Version: $LATEST
Unable to import module 'list': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: ba085c42-8de0-1153-cfa6-fd5c214ad777
REPORT RequestId: ba085c42-8de0-1153-cfa6-fd5c214ad777  Duration: 37.05 ms      Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 27 MB

**Comment by pwhitehead** [comment]
No not as yet.   Just going to continue under the C:\Users\<myuser> directory where I know it currently works.
You able to get it to work in this same directory?
